---
- name: Copy run-hooks wrapper
  copy:
    dest: /etc/dehydrated/run-hooks.pl
    src: run-hooks.pl
    owner: root
    group: root
    mode: 0700

- name: Create hooks.d
  file:
    dest: /etc/dehydrated/hooks.d
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Generate 90deploycert hook
  template:
    src: 90deploycert.j2
    dest: /etc/dehydrated/hooks.d/90deploycert
    owner: root
    group: root
    mode: "0700"
  when: dehydrated_deploycert is defined

- name: Remove 90deploycert hook
  file: dest=/etc/dehydrated/hooks.d/90deploycert state=absent
  when: dehydrated_deploycert is not defined

- name: Deploy script with custom hooks
  template:
    src: hooks.j2
    dest: /etc/dehydrated/hooks.d/50customhooks
    owner: root
    group: root
    mode: "0700"
  when: dehydrated_hooks is defined

- name: Remove script with custom hooks
  file: dest=/etc/dehydrated/hooks.d/50customhooks state=absent
  when: dehydrated_hooks is not defined

- name: Deploy custom hooks
  copy:
    src: "{{ item.src }}"
    dest: "/etc/dehydrated/hooks.d/{{ item.name|default(item.src|basename) }}"
    owner: root
    group: root
    mode: 0700
  when: item.state|default('present') == "present"
  loop: "{{ dehydrated_hook_scripts }}"

- name: Remove custom hooks with state absent
  file:
    path: "/etc/dehydrated/hooks.d/{{ item.name|default(item.src|basename) }}"
    state: absent
  when: item.state|default('present') == "absent"
  loop: "{{ dehydrated_hook_scripts }}"
