---
- name: Install dehydrated dependencies
  apt: name={{item}}
  with_items: "{{ dehydrated_dependencies }}"

- name: Checkout dehydrated from github
  git:
    repo: "https://github.com/lukas2511/dehydrated.git"
    update: "{{ dehydrated_update }}"
    dest: "{{ dehydrated_install_root }}"
    version: "{{ dehydrated_version }}"

- name: Create /etc/dehydrated
  file: dest=/etc/dehydrated state=directory owner=root group=root mode=0700

- name: Create wellknown challenge directory
  file:
    path: "{{ dehydrated_wellknown }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: dehydrated_wellknown is defined

- name: Generate dehydrated config
  template:
    dest: /etc/dehydrated/config
    src: config.j2
    owner: root
    group: root
    mode: 0600

- name: Generate dehydrated domains.txt
  copy:
    dest: /etc/dehydrated/domains.txt
    content: "{{ dehydrated_domains }}"
    owner: root
    group: root
    mode: 0600
  notify: run dehydrated

- import_tasks: hooks.yml

- name: Include dns-01-lexicon.yml
  include_tasks: dns-01-lexicon.yml
  when:
    - dehydrated_challengetype == 'dns-01'
    - dehydrated_use_lexicon

- name: Install cronjob
  cron:
    name: dehydrated-renew
    minute: "{{ 59|random(seed=inventory_hostname) }}"
    hour: "{{ 4|random(seed=inventory_hostname) }}"
    user: root
    job: "{{ dehydrated_install_root }}/dehydrated -c"
    cron_file: dehydrated
    state: "{{ 'present' if dehydrated_cronjob else 'absent' }}"

- import_tasks: systemd.yml

# /opt/dehydrated/dehydrated --register --accept-terms
- name: Check if already registered
  stat:
    path: "/etc/dehydrated/accounts/{{ ((dehydrated_ca + '\n')|b64encode).rstrip('=').replace('+', '-').replace('/', '_') }}"
  register: ca_stat

- block: # block register
  - assert:
      that: dehydrated_accept_letsencrypt_terms

  - name: Register to CA
    command: "{{ dehydrated_install_root }}/dehydrated --register --accept-terms"
  # \end block register
  when: "not ca_stat.stat.exists or (ca_stat.stat.isdir is defined and not ca_stat.stat.isdir)"

- meta: flush_handlers
